#pragma once

#define PLANET_GRID_HEIGHT 5
#define PLANET_GRID_WIDTH 5
#define START_PREDATOR_COUNT 5
#define START_PREY_COUNT 10
#define START_FOOD_SOURCE_COUNT 500
#define DAY_COUNT 5

#define PREY_STARTING_CALORIES 10
#define PREDATOR_STARTING_CALORIES 10

