#pragma once

#define PLANET_GRID_HEIGHT 10
#define PLANET_GRID_WIDTH 10
#define START_PREDATOR_COUNT 5
#define START_PREY_COUNT 10
#define START_FOOD_SOURCE_COUNT 500
#define DAY_COUNT 30

#define PREY_STARTING_CALORIES 9999
#define PREDATOR_STARTING_CALORIES 10

