#pragma once

#define PLANET_GRID_HEIGHT 5
#define PLANET_GRID_WIDTH 5
#define START_PREDATOR_COUNT 5
#define START_PREY_COUNT 10
#define START_FOOD_SOURCE_COUNT 500
#define DAY_COUNT 5

#define ORGANISM_STARTING_CALORIES 10

#define MIN_ORGANISM_STRENGTH 0
#define MAX_ORGANISM_STRENGTH 10
#define MIN_ORGANISM_OFFSPRING_CAPACITY 0
#define MAX_ORGANISM_OFFSPRING_CAPACITY 5
#define MIN_ORGANISM_CALORIE_USAGE 1
#define MAX_ORGANISM_CALORIE_USAGE 5
