PREY = "PREY"
PREDATORS = "PREDATORS"
FOOD = "FOOD"
POSITION_LOCK = "POSITION_LOCK"

STRENGTH = "STRENGTH"
OFFSPRING_CAPACITY = "OFFSPRING_CAPACITY"
CALORIE_USAGE = "CALORIE_USAGE"

PROCESS = "PROCESS"
TRANSITION = "TRANSITION"
DONE = "DONE"

ALIVE_COUNT = "ALIVE_COUNT"
STARVED = "STARVED"
CREATED = "CREATED"
EATEN = "EATEN"
